// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Tpqr-sPRLSyQ_eH51P8cWT87-nnY67w',
    appId: '1:286158150368:web:988a508a5edc700b808e85',
    messagingSenderId: '286158150368',
    projectId: 'todoriverpodflutter',
    authDomain: 'todoriverpodflutter.firebaseapp.com',
    storageBucket: 'todoriverpodflutter.firebasestorage.app',
    measurementId: 'G-77RX5JS982',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfj0ymF_uUpsce7WX2-QV7MTQcHu-qyE',
    appId: '1:286158150368:android:097ebd5bf0eb4a90808e85',
    messagingSenderId: '286158150368',
    projectId: 'todoriverpodflutter',
    storageBucket: 'todoriverpodflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvGwubs5xajT59v8MsBjeAh1M5urwyt4',
    appId: '1:286158150368:ios:ddd4a460cca737ea808e85',
    messagingSenderId: '286158150368',
    projectId: 'todoriverpodflutter',
    storageBucket: 'todoriverpodflutter.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMvGwubs5xajT59v8MsBjeAh1M5urwyt4',
    appId: '1:286158150368:ios:ddd4a460cca737ea808e85',
    messagingSenderId: '286158150368',
    projectId: 'todoriverpodflutter',
    storageBucket: 'todoriverpodflutter.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Tpqr-sPRLSyQ_eH51P8cWT87-nnY67w',
    appId: '1:286158150368:web:8615ba36e1d10dec808e85',
    messagingSenderId: '286158150368',
    projectId: 'todoriverpodflutter',
    authDomain: 'todoriverpodflutter.firebaseapp.com',
    storageBucket: 'todoriverpodflutter.firebasestorage.app',
    measurementId: 'G-TF1PZKRZPX',
  );
}
